site_name: plumipy

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - index.md
  - quickstart.md
  - developer.md
